### ISSUE TITLE
Haproxy ingress controller 3.1.0 with haproxy 3.1.3 breaking for me

### ISSUE THREAD

**Issue by cxfcxf** [haproxytech/kubernetes-ingress#700]
We are running them as external mode with haproxy ingress 3.0.2 and haproxy 3.0.8 no issue

when i start to testing Harpoxy ingress controller 3.1.0 with Haproxy 3.1.3, haproxy ingress controller failed to start

the log point to a panic to start so i dig along and find the issue is haproxy can not start.

```bash
# /app/haproxy/bin/haproxy -S /var/haproxy-ingress/run/haproxy-master.sock,level,admin -f /var/haproxy-ingress/etc/haproxy.cfg
[NOTICE]   (573937) : haproxy version is 3.1.3-929bedf
[NOTICE]   (573937) : path to executable is /app/mgni-haproxy/bin/mgni-haproxy
[ALERT]    (573937) : a master CLI socket was defined, but master-worker mode (-W) is not enabled.
```

when i add `-W` in to the command
```bash
# /app/haproxy/bin/haproxy -W -S /var/haproxy-ingress/run/haproxy-master.sock,level,admin -f /var/haproxy-ingress/etc/haproxy.cfg
[NOTICE]   (573973) : Initializing new worker (573974)
[NOTICE]   (573974) : haproxy version is 3.1.3-929bedf
[NOTICE]   (573974) : path to executable is /app/mgni-haproxy/bin/mgni-haproxy
[WARNING]  (573974) : frontend 'healthz' has no 'bind' directive. Please declare it as a backend if this was intended.
[WARNING]  (573974) : frontend 'stats' has no 'bind' directive. Please declare it as a backend if this was intended.
```

it is able to start

and when i check back in haproxy 3.0.8, it seems it doesnt require `-W` to start
```bash
]# /app/haproxy/bin/haproxy -S /var/haproxy-ingress/run/haproxy-master.sock,level,admin -f /var/haproxy-ingress/etc/haproxy.cfg
[NOTICE]   (2559947) : New worker (2559948) forked
```

i did a brief grep on the code base of ingress controller, i dont see `-W` is in anywhere

is this a new feature? or the 3.1.0 ingress controller doesnt work with haproxy 3.1.3?

or i m missing some config that need to be enabled?

**Comment by ivanmatmati** [comment]
Hi @cxfcxf , Thanks for reporting, we've spotted this issue and this is fixed in master branch. It will be available in the next release. You can test it with nightly build by changing your docker image version to "nightly".

**Comment by cxfcxf** [comment]
hmm, so i pulled master branch and build it myself

its still not working cause
```bash
2025/02/14 11:40:13 INFO    controller/controller.go:104  Stopping Ingress Controller
2025/02/14 11:40:13 ERROR   controller/controller.go:106  waitid: no child processes
```

**Comment by cxfcxf** [comment]
Hi, i think the current master still breaks, the panic is from native-client v6 6.0.7 v2v3 global_convert.go, i have to use the old commit before v3 API and force it to use client-native v6@6.0.6
