### ISSUE TITLE
hap-ingress in external mode not updating certificates on disk (sporadic)

### ISSUE THREAD

**Issue by joachimbuechse** [haproxytech/kubernetes-ingress#721]
**Setup:**

- Two instances of hap-ingress (3.1.6/3.1.7) running on debian serving as (redundant) external ingress controllers for k8s.
- Identical setup / versions of both instances
- Pipeline updating certificates by replacing (updating) tls secrets issued by letsencrypt in k8s

**Problem:** 

- update of tls secret in k8s leads to replacement of the runtime certificate in haproxy (good) but not of the file on disk (problem).
- the problem happens sporadically only (i.e. sometimes both hapi instances replace the disk file, sometimes only one does)

**Analysis:**

This happens only sporadically. I can see that another cert was successfully updated on disk by both hapi instances just 2 days before. No errors / warnings in the hapi logs.

The disk file is replaced only on one instance

_Checked with_

```
ls -ltr /opt/haproxy-ingress/config/certs/frontend/
openssl x509 -enddate -noout -in certs/frontend/haproxy-ingress_epg.[snip].pem

```
The runtime cert is replaced on both instances

_Checked with_

`openssl s_client -connect [snip]:443 -servername epg.[snip] < /dev/null 2>/dev/null | openssl x509 -noout -enddate -subject
`

The (defunct) instance is no longer returning a valid certificate chain (i.e. issuer cert is missing)

_Checked with_

`openssl s_client -connect [snip]:443 -servername epg.[snip] < /dev/null 2>/dev/null
`
OK instance:

```
depth=2 C=US, O=Internet Security Research Group, CN=ISRG Root X1
verify return:1
depth=1 C=US, O=Let's Encrypt, CN=R10
verify return:1
depth=0 CN=epg.[snip]
verify return:1
---
Certificate chain
 0 s:CN=epg.[snip]
   i:C=US, O=Let's Encrypt, CN=R10
   a:PKEY: RSA, 2048 (bit); sigalg: sha256WithRSAEncryption
   v:NotBefore: May 21 06:40:13 2025 GMT; NotAfter: Aug 19 06:40:12 2025 GMT
 1 s:C=US, O=Let's Encrypt, CN=R10
   i:C=US, O=Internet Security Research Group, CN=ISRG Root X1
   a:PKEY: RSA, 2048 (bit); sigalg: sha256WithRSAEncryption
   v:NotBefore: Mar 13 00:00:00 2024 GMT; NotAfter: Mar 12 23:59:59 2027 GMT

```

Defunct instance:

```
depth=0 CN=epg.[snip]
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=epg.[snip]
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=epg.[snip]
verify return:1
---
Certificate chain
 0 s:CN=epg.[snip]
   i:C=US, O=Let's Encrypt, CN=R10
   a:PKEY: RSA, 2048 (bit); sigalg: sha256WithRSAEncryption
   v:NotBefore: May 21 06:40:13 2025 GMT; NotAfter: Aug 19 06:40:12 2025 GMT

```

Clueless as to how to debug this further. Any help appreciated.

**Comment by hdurand0710** [comment]
Hello @joachimbuechse ,

The certificates are written on disk only if there a haproxy reload. The runtime certificates are updated in any case, and it seems it's ok for you.
It's possible that on the instance where the certificate is not updated on disk, there was no reload. You could check if that's the case.

There is also a startup [--disable-writing-only-if-reload](https://github.com/haproxytech/kubernetes-ingress/blob/master/documentation/controller.md#--disable-writing-only-if-reload)  flag that disable this behaviour and always update the certificates on disk immediatly (even if no reload of haproxy is happening).

**Comment by joachimbuechse** [comment]
Thanks for the answer, I will test the option --disable-writing-only-if-reload.

I've also updated the original ticket description as I missed the most important part in the ticket. When this situation happens, hapi does not return a full certificate chain but only the site cert itself.

**Comment by joachimbuechse** [comment]
I've tested with  --disable-writing-only-if-reload  and without. The option is apparently not required for certificate writing. I just pushed an older tls secret. Two instances of hapi one configured with the option


```
[root@slb-ms07.prep.qltv]:/opt/haproxy-ingress/config/certs/frontend # ps -edf | grep haproxy-ingress-controller
root     2021194       1  0 10:04 ?        00:00:01 /usr/local/bin/haproxy-ingress-controller --program=/usr/sbin/haproxy --config-dir=/opt/haproxy-ingress/config --maps-dir=/opt/haproxy-ingress/config/maps --disable-writing-only-if-reload --runtime-dir=/tmp/haproxy-ingress --external --ingress.class=public-ingress --configmap=haproxy-ingress/public-ingress --default-backend-service=default/deny-all --ipv4-bind-address=[snip]--disable-ipv6 --http-bind-port=80 --https-bind-port=443 --stats-bind-port=8404

```
the other without

```
[root@slb-ms08]:/opt/haproxy-ingress/config/certs/frontend # ps -edf | grep ingress
root     1503906       1  0 Apr08 ?        00:21:05 /usr/local/bin/haproxy-ingress-controller --program=/usr/sbin/haproxy --config-dir=/opt/haproxy-ingress/config --maps-dir=/opt/haproxy-ingress/config/maps --runtime-dir=/tmp/haproxy-ingress --external --ingress.class=public-ingress --configmap=haproxy-ingress/public-ingress --default-backend-service=default/deny-all --ipv4-bind-address=[snip] --disable-ipv6 --http-bind-port=80 --https-bind-port=443 --stats-bind-port=8404

```

Both updated the file in /opt/haproxy-ingress/config/certs/frontend/.


I can't yet say if the option is making a difference in terms of reliability of writing as this issue happens sporadically only for us.

**Comment by jgoldschrafe** [comment]
This issue may be broader in scope than certificates. My team recently experienced an issue where many services became unreachable across our infrastructure in a way that was consistent with HAProxy reloading deeply stale backend-to-IP mappings from disk. Unfortunately, in our urgency to resolve the production incident, we were unable to collect much supporting data. We'll be following up on that, but hopefully this is useful as a single data point in the interim.

As the incident occurred a few days after an upgrade from 3.0.4 to 3.1.7, we're scrutinizing the parallel filesystem write changes around https://github.com/haproxytech/kubernetes-ingress/commit/1b84fd904b5ff75795f8294552f0a08621f9ef53 and https://github.com/haproxytech/kubernetes-ingress/commit/38f57e8332781ab0e230597655beac4270d88f87 as starting points for our internal investigation. Again, there's no data to directly implicate these changes, but they seem like the area where this sort of bug would be most likely to be introduced.

**Comment by oktalz** [comment]
@zadjadr we will try to figure out what is happening, 
just because we weren't able to reproduce it does not mean its working as it should.

I'll keep this open and try to see if we can do something

**Comment by oekarlsson** [comment]
We have also experienced this problem since an upgrade during spring time in one cluster. The problem has happended three times, the last one today. The certificate and the secret created by cert-manager is all fine, but haproxy is using an older one. The solution is to force a rolling update of the pods. When they are restarted, everything is OK. To only reload configuration is not enough.

**Comment by oekarlsson** [comment]
> We have also experienced this problem since an upgrade during spring time in one cluster. The problem has happended three times, the last one today. The certificate and the secret created by cert-manager is all fine, but haproxy is using an older one. The solution is to force a rolling update of the pods. When they are restarted, everything is OK. To only reload configuration is not enough.

Notice: We are not running in external mode. We installed using the helm chart with some custom configuration.

**Comment by hdurand0710** [comment]
Issue was found and a fix is available d0a6717e65bc6e7a50194af3ece637a3a858bbd5 in branches master and 3.2.
It will then be available in the next 3.2 release

**Comment by joachimbuechse** [comment]
We have tested the fixes that were implemented (i.e. upgraded from the working 3.0.9 to 3.2) unfortunately the issues still exists for us.


On cert renewal one instance has updated the certs properly 

```shell
openssl s_client -servername canary-preprod.qltv.[snip] -showcerts -connect [snip].173.90:443 | grep Verification </dev/null
Connecting to [snip].173.90
depth=2 C=US, O=Internet Security Research Group, CN=ISRG Root X1
verify return:1
depth=1 C=US, O=Let's Encrypt, CN=R12
verify return:1
depth=0 CN=canary-preprod.qltv.[snip]
verify return:1
Verification: OK
``` 

the other instance returns a broken cert chain without issuer cert
``` 
openssl s_client -servername canary-preprod.qltv.[snip] -showcerts -connect [snip].173.91:443 | grep Verification </dev/null
Connecting to [snip].173.91
depth=0 CN=canary-preprod.qltv.[snip]
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=canary-preprod.qltv.[snip]
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=canary-preprod.qltv.[snip]
verify return:1
Verification error: unable to verify the first certificate 
``` 

``` 
root@slb-msext02:~# /usr/local/bin/haproxy-ingress-controller --version
2026/04/23 14:11:02 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
HAProxy Ingress Controller dev f8ae6334
Build from: [github.com/haproxytech/kubernetes-ingress](http://github.com/haproxytech/kubernetes-ingress)
Git commit date: 2026-02-17T06:59:59Z
Ingress Management: default implementation

root@slb-msext02:~# /usr/sbin/haproxy -v
HAProxy version 3.2.15-1ppa1~noble 2026/03/21 - https://haproxy.org/
Status: long-term supported branch - will stop receiving fixes around Q2 2030.
Known bugs: http://www.haproxy.org/bugs/bugs-3.2.15.html
Running on: Linux 6.8.0-110-generic #110-Ubuntu SMP PREEMPT_DYNAMIC Thu Mar 19 15:09:20 UTC 2026 x86_64
```

**Comment by cbarbian-sap** [comment]
We still see that error with 3.2.3, too.

After rotating a certificate, haproxy often (maybe always?) sends an incomplete chain, containing only the leaf; intermediates are missing.

Reloading haproxy (via the admin socket) makes it use the previous certificate chain. Which may work (if the previous certificate is not yet expired), but this is no solution of course.

The only fix is to restart it completely (recreate pod).

**Comment by hdurand0710** [comment]
Hi,
A new fix has been committed 9e6a31d3baa9b96b2dc99c461f949f65f985dde2 on branch v3.2 (release >= 3.2.7).
Can you upgrade to a version >= 3.2.7 and let us know if this still happens ?

**Comment by joachimbuechse** [comment]
Sorry for the slow response. We very much appreciate that you are still trying to fix the issue.

I'm (again) trying to get to the bottom of this issue. I have one instance that exhibits the error currently.

Here are some observations:

- we have 2 haproxy master + 2 haproxy worker processes running at the same time (that is obviously not good)
- they receive very few requests and both instances are running since a long time (one since april, the other since this morning)
- the -sf parameter of the newer one does NOT show the pid of the older one
- all processes are listening on 80 + 443 so new connections are randomly dispatched to old or new
- one returns broken cert chains, the other not

I'm aware this is potentially a new edge case and unfortunately the logs of haproxy + ingress have been cycled, so I can not reproduce what happened from the logs. I.e. why the old haproxy instance was still around.

This host was running haproxy version 3.2.15-1ppa1~noble and haproxy-ingress-controller_3.2.6_Linux_x86_64. I have now updated this host to the latest versions hap (3.2.19) + hapi (3.2.11). I will report back when / if we run into the issue again.

**Comment by hdurand0710** [comment]
@joachimbuechse , 
Can you specify the KIC version for which you still have the issue ?
Thanks

**Comment by joachimbuechse** [comment]
> [@joachimbuechse](https://github.com/joachimbuechse) , Can you specify the KIC version for which you still have the issue ? Thanks

Can you please clarify what you mean by "KIC"?

**Comment by hdurand0710** [comment]
@joachimbuechse 
KIC = Kubernetes Ingress Controller
I also missed your last sentence (sorry !) where you did specify that you last noticed the issue with ingress controller version 3.2.6.
The latest fix, regarding the broken certificate chain has been released in version 3.2.7.
As  you have upgraded to version 3.2.11, it should be fixed.

Let us know if it's not fixed with the 3.2.11 version. We will keep digging then.
Thanks for your time.
